// AI commit explanation modal — asks the provider to explain what a commit
// changed and why it matters. Read-only: the output is advice, nothing is
// applied to the repository (P1). Reused by CommitInfoHeader and the
// AI command palette.

import { useEffect, useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Copy, RefreshCw } from "lucide-react";
import { explainCommit, formatAppError } from "@/lib/api";
import { Button } from "@/components/ui/Button";
import { Modal } from "@/components/ui/Modal";
import { useStatusAreaStore } from "@/stores/statusAreaStore";

export function CommitExplainModal({
  workspaceId,
  sha,
  subject,
  open,
  onClose,
}: {
  workspaceId: string;
  sha: string;
  /** Commit subject for the dialog title (short text from the caller). */
  subject?: string;
  open: boolean;
  onClose: () => void;
}): React.JSX.Element {
  const [text, setText] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [provider, setProvider] = useState<string | null>(null);
  const setStatus = useStatusAreaStore((s) => s.setStatus);

  const genMut = useMutation({
    mutationFn: () => explainCommit(workspaceId, sha),
    onSuccess: (res) => {
      setText(res.text);
      setProvider(res.provider_used);
      setError(null);
      if (res.used_fallback) {
        setStatus(`Primary AI provider failed — response served by ${res.provider_used}`, "info");
      }
    },
    onError: (e) => setError(formatAppError(e)),
  });

  // Fresh explanation each time the modal opens; regenerate is manual.
  useEffect(() => {
    if (!open) return;
    setText("");
    setError(null);
    setProvider(null);
    genMut.mutate();
    // eslint-disable-next-line react-hooks/exhaustive-deps -- run once per open
  }, [open, workspaceId, sha]);

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(text);
      setStatus("Explanation copied to clipboard");
    } catch {
      setStatus("Clipboard unavailable", "danger");
    }
  };

  const title = subject ? `Explain: ${subject}` : `Explain ${sha.slice(0, 7)}`;

  return (
    <Modal
      open={open}
      onOpenChange={(next) => {
        if (!next) onClose();
      }}
      title={title.length > 80 ? `${title.slice(0, 77)}…` : title}
      description="What this commit changed, in plain language. AI advice only — nothing is applied."
      size="lg"
      footer={
        <>
          {provider && !genMut.isPending ? (
            <span className="mr-auto text-[11px] text-text-muted">Generated by {provider}.</span>
          ) : null}
          <Button
            variant="ghost"
            size="sm"
            disabled={genMut.isPending}
            onClick={() => genMut.mutate()}
          >
            <RefreshCw size={13} />
            Regenerate
          </Button>
          <Button
            variant="secondary"
            size="sm"
            disabled={!text || genMut.isPending}
            onClick={() => void copy()}
          >
            <Copy size={13} />
            Copy
          </Button>
        </>
      }
    >
      <div className="flex flex-col gap-3">
        {genMut.isPending ? (
          <p className="text-xs text-text-muted">Thinking…</p>
        ) : error ? (
          <p className="text-xs text-danger">{error}</p>
        ) : text ? (
          <div className="max-h-[50vh] overflow-auto rounded-md border border-border-subtle bg-bg-primary px-3 py-2 text-xs leading-5 whitespace-pre-wrap break-words text-text-secondary select-text">
            {text}
          </div>
        ) : null}
      </div>
    </Modal>
  );
}
