// AI PR description modal — generates a copy-ready title + markdown body
// for the active branch vs the default base branch. Nothing is pushed or
// created remotely (P1): the user copies the text into their PR tool.

import { useEffect, useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Copy, RefreshCw } from "lucide-react";
import { formatAppError, generatePrDescription } from "@/lib/api";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { Modal } from "@/components/ui/Modal";
import { Textarea } from "@/components/ui/Textarea";
import { useStatusAreaStore } from "@/stores/statusAreaStore";

export function PrDescriptionModal({
  workspaceId,
  open,
  onClose,
}: {
  workspaceId: string;
  open: boolean;
  onClose: () => void;
}): React.JSX.Element {
  const [title, setTitle] = useState("");
  const [body, setBody] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [provider, setProvider] = useState<string | null>(null);
  const setStatus = useStatusAreaStore((s) => s.setStatus);

  const genMut = useMutation({
    mutationFn: () => generatePrDescription(workspaceId),
    onSuccess: (res) => {
      setTitle(res.title);
      setBody(res.body);
      setProvider(res.provider_used);
      setError(null);
      if (res.used_fallback) {
        setStatus(`Primary AI provider failed — response served by ${res.provider_used}`, "info");
      }
    },
    onError: (e) => setError(formatAppError(e)),
  });

  // Fresh generation each time the modal opens; the user can regenerate.
  useEffect(() => {
    if (!open) return;
    setTitle("");
    setBody("");
    setError(null);
    setProvider(null);
    genMut.mutate();
    // eslint-disable-next-line react-hooks/exhaustive-deps -- run once per open
  }, [open, workspaceId]);

  const copy = async (text: string, label: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setStatus(`${label} copied to clipboard`);
    } catch {
      setStatus("Clipboard unavailable", "danger");
    }
  };

  return (
    <Modal
      open={open}
      onOpenChange={(next) => {
        if (!next) onClose();
      }}
      title="AI PR description"
      description="Generated for the active branch vs the default base. Edit freely, then copy — nothing is created remotely."
      size="lg"
    >
      <div className="flex flex-col gap-3">
        <label className="flex flex-col gap-1 text-xs text-text-secondary">
          Title
          <Input
            value={title}
            onChange={setTitle}
            placeholder="PR title"
            disabled={genMut.isPending}
          />
        </label>
        <label className="flex flex-col gap-1 text-xs text-text-secondary">
          Description (markdown)
          <Textarea
            value={body}
            onChange={setBody}
            rows={14}
            spellCheck={false}
            disabled={genMut.isPending}
            placeholder="PR description body"
            className="rounded-md px-2 py-1.5 font-mono text-[11px] leading-5"
          />
        </label>

        {genMut.isPending ? (
          <p className="text-xs text-text-muted">Generating with AI…</p>
        ) : error ? (
          <p className="text-xs text-danger">{error}</p>
        ) : provider ? (
          <p className="text-[11px] text-text-muted">Generated by {provider}.</p>
        ) : null}

        <div className="flex flex-wrap items-center justify-end gap-2">
          <Button
            variant="ghost"
            size="sm"
            disabled={genMut.isPending}
            onClick={() => genMut.mutate()}
          >
            <RefreshCw size={13} />
            Regenerate
          </Button>
          <Button
            variant="secondary"
            size="sm"
            disabled={!title || genMut.isPending}
            onClick={() => void copy(title, "Title")}
          >
            <Copy size={13} />
            Copy title
          </Button>
          <Button
            variant="secondary"
            size="sm"
            disabled={!body || genMut.isPending}
            onClick={() => void copy(body, "Description")}
          >
            <Copy size={13} />
            Copy description
          </Button>
          <Button
            variant="primary"
            size="sm"
            disabled={(!title && !body) || genMut.isPending}
            onClick={() => void copy(`${title}\n\n${body}`.trim(), "PR description")}
          >
            <Copy size={13} />
            Copy all
          </Button>
        </div>
      </div>
    </Modal>
  );
}
